services:
  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - USER_NAME=test
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=secret
      - SUDO_ACCESS=true
    ports:
      - "2222:2222"

  sshgate:
    build: .
    depends_on:
      - ssh
    stdin_open: true
    command:
      - "--host=ssh"
      - "--port=2222"
      - "--user=test"
      - "--password=secret"


